# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: http://localhost:18081
          predicates:
            - Path=/ms1/**
            
server:
  port: 8080
